trigger:
  branches:
    include:
      - main 

pool: self-hosted-1

variables:
  dockerimagename: 'parikshit2097/nodeapp-azure'  # Set the desired Docker image name here

stages:
  - stage: CheckoutSource
    displayName: 'Checkout Source'
    steps:
      - checkout: git://parikshit-2706/k8s-secrets

  - stage: BuildImage
    displayName: 'Build image'
    steps:
      - script: |
          docker build -t $(dockerimagename) .
        displayName: 'Build Docker image'
  
  - stage: PushImage
    displayName: 'Pushing Image'
    environment:
      name: dockerhublogin
    steps:
      - script: |
          docker login -u parikshit2097 -p thisIsMyDocker@1357
          docker push $(dockerimagename):latest
        displayName: 'Push Docker image to Docker Hub'
  
  - stage: DeployAppToKubernetes
    displayName: 'Deploying App to Kubernetes'
    steps:
      - script: |
          kubectl apply -f deploymentservice.yml --kubeconfig 'k8s'
        displayName: 'Deploy to Kubernetes'
