---
apiVersion: v1
data:
  parikshit.conf: |
    Parikshit's conf file, hi there!
kind: ConfigMap
metadata:
  name: parikshit-configmap-az
  namespace: 1911
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-1-az
  namespace: 1911
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-azure
  namespace: 1911
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000
        volumeMounts:
         - name: testconfigmap
           mountPath: "/tmp/config" 
         - name: testsecret
           mountPath: /tmp/mysecrets
      volumes:
        - name: testconfigmap
          configMap:
            name: parikshit-configmap-az
            items:
              - key: parikshit.conf
                path: parikshit.conf
        - name: testsecret
          secret:
            secretName: mysecret-1-az

---

 

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-azure
  namespace: 1911
spec:
  selector:
    app: nodeapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31150
