---
apiVersion: v1
data:
  parikshit.conf: |
    Parikshit's conf file, hi there!
kind: ConfigMap
metadata:
  name: confmap-parikshit
  namespace: 1911
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-1
  namespace: 1911
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-pc-returns
  namespace: 1911
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000
        volumeMounts:
         - name: testsecret
           mountPath: "/tmp/config" 
         - name: testsecret
           mountPath: /tmp/mysecrets
      volumes:
        - name: testconfigmap
          configMap:
            name: confmap-parikshit
            items:
              - key: parikshit.conf
                path: parikshit.conf
        - name: testsecret
          secret:
            secretName: mysecret-1

---

 

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-returns
  namespace: 1911
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31120
